docs/keyboard-shortcuts.md

docs: keyboard shortcuts

---

docs/error.md

docs: error

---

docs/events.md
docs/player-states.md

docs: events

---

docs/errors.md

change the error message format

docs: error printing

---

docs/embed-types.md

chore: update embed type docs

---

package.json
yarn.lock

chore: upgrade shaka to v2.3.3

---

docs/events.md

docs: events list link was faulty

---

README.md
docs/coding-guidlines.md
docs/getting-started-using-player-studio.md
docs/managing-tracks.md
docs/player-states.md
docs/playing-your-video.md
docs/user-preferences.md

Just several typo fixes in README.

docs: fixed license href and several typos.

---

src/common/plugins/plugins-config.json

Configure `googleAnalytics` with kaltura parameters

feat(FEC-8036): google analytics

---

src/common/plugins/plugins-config.js

consider the application config and uiconf while kaltura params evaluation

fix(FEC-8204): cannot set entry id via plugin config

---

src/common/utils/kaltura-params.js
src/index.html
src/kaltura-player.js
test/src/common/utils/kaltura-params.spec.js

Change the new player config by reference and then configure it to the player.

fix(FEC-8202): Session ID isn't sent when reporting analytics

---

package.json
src/index.js
yarn.lock

These plugins are served as external bundle 
https://github.com/kaltura/playkit-js-youbora/pull/20
https://github.com/kaltura/playkit-js-ima/pull/61

feat: remove youbora & ima plugins from kaltura player bundle

---

package.json
yarn.lock

updating the shaka player version to support pwa

chore: update shaka-player version 2.3.3-k-3

---

src/ott/poster.js

Fix wrong curly brackes place.

fix(FEC-8261): OTT Poster is now an object - we tried to load [Object Object] url 

---

src/common/plugins/plugins-config.js
src/common/utils/evaluate.js
test/src/common/utils/ui-wrapper.spec.js

* evaluate `false` and `0` values
* parse string to boolean and number when applicable ("false", "1" etc.)

fix(FEC-8349): OTT analytics - no event send for logged user

---

src/common/plugins/plugins-config.json

Add player version via comscore plugin config

fix(FEC-8356): pass player version string via config

---

test/src/common/utils/ui-wrapper.spec.js

revert removing destroy from test https://github.com/kaltura/kaltura-player-js/pull/134
as it fixed by https://github.com/kaltura/playkit-js-ui/pull/252

chore: fix destroy test

---

src/common/plugins/plugins-config.js

forgot to pass value param to evaluation method

fix(FEC-8375): plugins data not evaluated

---

package.json
yarn.lock

update shaka version to support pwa anti failure mechanism

feat: support download manager anti-failure mechnism

---

docs/configuration.md

Link to each PK config (e.g `PKPlaybackConfigObject`)

docs: link to PK's configuration page

---

src/common/polyfills/all.js
src/common/polyfills/prepend.js

fix(FEC-8530): element prepend is not supported on IE11

---

docs/playing-your-video.md

fix(docs): add assetReferenceType to mediaInfo

---

README.md
docs/api.md
docs/configuration.md
package.json
src/common/cast/base-remote-player.js
src/common/cast/cast-event-type.js
src/common/cast/player-snapshot.js
src/common/cast/remote-control.js
src/common/cast/remote-payload.js
src/common/cast/remote-player-ui.js
src/common/cast/remote-player.js
src/common/cast/remote-session.js
src/common/plugins/plugins-config-store.js
src/common/plugins/plugins-config.js
src/common/storage/storage-manager.js
src/common/storage/storage-wrapper.js
src/common/ui-wrapper.js
src/common/utils/evaluate.js
src/common/utils/external-stream-redirect-helper.js
src/common/utils/kaltura-params.js
src/common/utils/logger.js
src/common/utils/setup-helpers.js
src/common/utils/thumbs.js
yarn.lock

docs: cast framework

---

src/kaltura-player.js

expose getter for the plugins instances.

feat: expose plugins getter

---

src/common/cast/base-remote-player.js
src/common/cast/player-snapshot.js
src/common/cast/remote-player.js
src/common/cast/text-style-convertor.js
src/common/playlist/playlist-manager.js
src/common/playlist/playlist.js
src/common/plugins/plugins-config-store.js
src/common/plugins/plugins-config.js
src/kaltura-player.js

fix: expose picture in picture api

---

samples/ovp/playlist-by-entry-list.html
src/common/playlist/playlist-manager.js
src/kaltura-player.js

use `autoplay` config for the second entry and onwards

fix(FEC-8588): large play button displayed for a sec before the next item is playing

---

docs/api.md
flow-typed/types/playlist-config.js
flow-typed/types/playlist-countdown-options.js
flow-typed/types/playlist-item-config.js
flow-typed/types/playlist-metadata.js
flow-typed/types/playlist-options.js
src/common/playlist/index.js
src/common/playlist/playlist-event-type.js
src/common/playlist/playlist-item.js
src/common/playlist/playlist-manager.js
src/index.js

docs: playlist

---

src/common/playlist/playlist-manager.js

fire `PLAYLIST_ITEM_CHANGED` after `setMedia` or `loadMedia`

fix(FEC-8689): PLAYLIST_ITEM_CHANGED event fired before item has been changed

---

src/index.js

Changing the import to the regular method.
Babel does not handle it well and it causes transpiling issues results with the player cannot be loaded in IE.

fix: export does not transpile correctly

---

src/common/playlist/playlist-manager.js

create a new playlist on playlist manager constructor

fix(FEC-8713): playlist by config not playing

---

.github/PULL_REQUEST_TEMPLATE.md

chore: typo in pull request template

---

docs/api.md
src/common/cast/base-remote-player.js
src/common/cast/remote-player.js

fix(FEC-8726): kalturaPlayer.config api is broken while casting

---

package.json
yarn.lock

fix(FEC-8780): captions not shown after seek

---

package.json
yarn.lock

fix(FEC-8788): fix shaka playready endianness for Tivo

---

samples/ovp/playlist-by-config.html
src/kaltura-player.js
test/src/kaltura-player.spec.js

support `playlist` config in `configure` method

fix: set playlist by configure method doesn't work

---

karma.conf.js
test/src/setup.spec.js

fixed failing test, because of the new caption style structure.

chore(FEC-8572): fix failing test

---

docs/playlist.md
samples/style.css

docs: add references and fix links

---

flow-typed/types/playlist.js

docs: update playlist options 

---

src/common/utils/setup-helpers.js

Add protection when using the Env object

fix(FEC-8927): player crash on Echo show browser

---

src/kaltura-player.js

Add default in kaltura player to the main container

fix(FEC-8826): default element is video container instead main container

---

src/common/utils/setup-helpers.js

fix(FEC-9052): allow player to load from partner 0

---

src/common/utils/setup-helpers.js

add default configuration for LG TV

fix(FEC-9067): playback error with ima on LG TV WebOS

---

src/common/ui-wrapper.js
src/common/utils/setup-helpers.js

Change every check of device.type to mobile or tablet instead, there are more device types which not relevant.

fix(FEC-9177): Smart TV showed as mobile device

---

src/common/utils/setup-helpers.js

set bumper config 
```
disableMediaPreload: true,
position: [0]
```
to avoid conflicts with dai plugin

fix: bumper and ima-dai integration

---

flow-typed/types/kaltura-player-options.js
flow-typed/types/log-level.js
package.json
src/common/utils/logger.js
src/common/utils/setup-helpers.js
src/index.js
src/setup.js
yarn.lock

add configuration logger options.
handler to output logs with customize function.
option to remove playerVersion from log.

feat(FEC-9023): more logger options

---

src/common/utils/setup-helpers.js
test/src/common/utils/setup-helpers.spec.js

send usage beacon for usages of player without partner - this will be used to understand when player is configured incorrectly.

feat(FEC-9024): send beacon for non partner usage

---

src/common/utils/setup-helpers.js
test/src/common/utils/setup-helpers.spec.js

set `bumper` default config according to the env and config

feat(FEC-9145): support non sibling video tags

---

src/kaltura-player.js

Consider plugins come from the provider

feat(FEC-9156): getting bumper from playback context

---

src/common/utils/setup-helpers.js

Add configuration to handle ads with MSE

feat(FEC-9227): support reInit of MSE

---

package.json
src/common/utils/setup-helpers.js
yarn.lock

fix: useNativeTextTrack doesn't change to true by default on MacOS

---

src/common/plugins/plugins-config.js

get Product version from uiConf.

feat(FEC-9326): report product version

---

src/kaltura-player.js

feat: new hasUserInteracted api

---

package.json
yarn.lock

chore(FEC-9267): upgrade hls.js to latest

---

webpack.config.ott.js
webpack.config.ovp.js

Copy the `translations` directory from `playkit-js-ui` (https://github.com/kaltura/playkit-js-ui/pull/485) to the `dist` folder
Solves FEC-9465

feat(FEC-9465): internationalization (i18n) - player localization

---

src/common/utils/setup-helpers.js

add `Env.device.model === 'iPhone'` condition

fix(FEC-9734): auto play doesn't works, if "playsinline"=false on all platforms

---

.travis.yml

add Travis config that doesn't exist in Kaltura player but exist in our other repositories.

build: align travis repo config

---

src/common/cast/remote-control.js

fix incorrect parameter (since #188)
Solves FEC-10155

fix(FEC-10155): text track language is incorrect on cast disconnecting

---

.travis.yml

dist was missing on the canary version.
commit added to branch master with dist.

build: add dist to master branch on every commit for canary releases

---

.travis.yml

build: update playkit dependencies for canary

---

docs/ui-configuration.md
docs/ui.md

Added docs explaining how to load external CSS file to the player.
following FEC-9649
solves FEC-10272

docs(FEC-10272): update docs with css config

---

package.json
src/index.js
src/ott/analytics.js
src/ovp/analytics.js
webpack.config.ott.js
webpack.config.ovp.js
yarn.lock

remove analytics plugins injection
Related to https://github.com/kaltura/server/pull/9592
Solves FEC-10291

feat(FEC-10291): migrate analytics plugins injection from kaltura player to server

---

package.json
yarn.lock

issue: shaka 3.0.x has an issue with some mpd formats.
solution: downgrade to 2.5.13 4K solved by configure

fix: downgrade Shaka from 3.0.x

---

docs/api.md
src/kaltura-player.js

Exposing crossOrigin getter and setter

fix(FEC-10404): media doesn't work properly on Safari browser - no video displayed - Regression bug

---

src/common/ui-wrapper.js

Expose the new [`UIManager.addComponent`](https://github.com/kaltura/playkit-js-ui/pull/538) api

feat(FEC-10076): add support for dynamic injection

---

package.json
yarn.lock

test: fix tests

---

samples/ovp/all-plugins.html
samples/ovp/change-media-clear.html
samples/ovp/change-media-drm.html
samples/ovp/custom-poster.html
samples/ovp/custom-preview-thumbnail.html
samples/ovp/playlist-by-config.html
samples/ovp/playlist-by-entry-list.html
samples/ovp/playlist-by-id.html
samples/ovp/standalone-ima.html
samples/ovp/ui-conf.html
src/index.html

After BE migration to AWS need to request env URLs using https.

chore: change samples urls to https

---

package.json

```husky``` entry is missing on package.json.

chore: lint-staged linters doesn't running on commit

---

docs/configuration.md
flow-typed/types/kaltura-player-options.js

Solves FEC-10924
See https://github.com/kaltura/playkit-js/pull/537

docs(FEC-10924): missing text section config docs

---

src/common/utils/thumbs.js
test/src/common/utils/thumbs.spec.js

Don't build the default thumbnail preview for live content 
Solves FEC-10961

feat(FEC-10961): show the thumbnail preview in live

---

package.json
yarn.lock

fix memory leak with webpack bundle process

fix(FEC-10995): update Shaka to 3.0.8

---

docs/api.md
src/common/playlist/playlist-item.js
src/common/playlist/playlist-manager.js
src/common/playlist/playlist.js
test/src/common/playlist/playlist-manager.spec.js

add `current` api to the playlist manager and add `index` field to the playlist item

feat(FEC-10640): add api to get the playlist current working item index

---

src/kaltura-player.js

make `attachMediaSource` and `detachMediaSource` public
Solves FEC-11077

feat(11077): expose api for restart the media source

---

src/common/utils/setup-helpers.js
test/src/common/utils/setup-helpers.spec.js

chore: send the default impression for the default partner

---

scripts/after_deploy.sh

adding webhook to invoke ci on new jenkins
updating webhook to invoke ci on new jenkins
- [] changes have been done against master branch, and PR does not conflict

build: update Jenkins trigger

---

package.json
yarn.lock

feat(FEC-11337): Upgrade hls.js to 1.0

---

package.json
yarn.lock

chore: skip unstable test

---

package.json
yarn.lock

for DASH transition from dynamic to static

feat(FEC-11423): upgrade shaka to 3.0.13

---

test/src/common/thumbnail-manager.spec.js
test/src/common/utils/setup-helpers.spec.js
test/src/kaltura-player.spec.js
test/src/ovp/poster.spec.js

Replace images in player tests with fake images
Resolves FEC-12161

fix(FEC-12161): Need to replace static jpg files in player tests

---

test/src/common/storage/storage-manager.spec.js
test/src/common/thumbnail-manager.spec.js
test/src/ovp/poster.spec.js
test/src/setup.spec.js

change entry id used in loadMedia for unit tests, because loadMedia fails for one specific entry

test: change entry id used in loadMedia in unit tests

---

test/src/common/storage/storage-manager.spec.js
test/src/common/thumbnail-manager.spec.js
test/src/ovp/poster.spec.js
test/src/setup.spec.js

some tests fail because of a bad loadMedia request, 
unit test changes made during investigation were reverted failed tests skipped

test: revert unit test changes and skip failed tests

---

package.json
yarn.lock

Upgrade shaka-player to version 3.3.3
Related PR: https://github.com/kaltura/playkit-js-dash/pull/197
Resolves FEC-12381

chore(FEC-12381): upgrade shaka-player to version 3.3.3

---

src/common/playlist/playlist-manager.js
src/kaltura-player.js

solves: FEC-12335
related prs:
https://github.com/kaltura/playkit-js/pull/659
https://github.com/kaltura/playkit-js-ui/pull/687

fix(FEC-12335): Side Panel Item gets refreshed in every 'change media'

---

package.json
yarn.lock

linked PR https://github.com/kaltura/playkit-js-dash/pull/206

feat(FEC-12491): Upgrade shaka-player v4.2.1

---

ts-typed/kaltura-player.d.ts

Expose withEventManager decorator in ts-types for use by playkit-js-related
Related PR: https://github.com/kaltura/playkit-js-related/pull/33
Resolves FEC-12844

fix(FEC-12844): Related - autoContinue: true - countdown not canceled 

---

package.json
yarn.lock

upgrade shaka player v4.3.3
FEC-12874

feat(FEC-12874): upgrade shaka player library to v4.3.3

---

types.d.ts

Add missing TS types to KalturaPlayer TS types
solves FEC-13122

fix(FEC-13122): Add missing TS types to KalturaPlayer TS types

---

.github/workflows/run_tests.yaml
types.d.ts

fix(FEC-13123): update TS file declarations 

---

docs/configuration.md

doc(FEC-13215): fix cast api url path

---

.github/workflows/trigger_canary.yaml

chore(FEC-13229): git actions

---

.github/workflows/trigger_canary.yaml

chore(FEC-13229): github actions

---

.github/workflows/trigger_canary.yaml

chore(FEC 13229): trigger build

---

.github/workflows/trigger_canary.yaml

chore(FEC-13229): trigger build

---

.github/workflows/run_prod.yaml
.github/workflows/run_tests.yaml
.github/workflows/trigger_canary.yaml

chore(FEC-13229): git action trigger

---

package.json
src/index_ott.html
yarn.lock

feat(FEC-13212): upgrade shaka player v4.3.7

---

types.d.ts

solves: https://kaltura.atlassian.net/browse/FEC-13187

fix(FEC-13187): upd types

---

types.d.ts

update Kaltura-player TS types - relevant for SEO

fix(FEC-13119): update Kaltura-player TS types - relevant for SEO

---

package.json
yarn.lock

Revert hls.js version
Resolves FEC-13293

fix(FEC-13293): revert hls.js version upgrade

---

src/common/utils/setup-helpers.js
src/index.js

solves FEC-13340
related PR: https://github.com/kaltura/playkit-js-seo/pull/5

fix(FEC-13340): export Kaltura start time query param (for SEO usage)

---

package.json
yarn.lock

solves FEC-13361
related pr: https://github.com/kaltura/playkit-js-dash/pull/248

fix(FEC-13361): Upgrade shaka latest

---

package.json
src/common/polyfills/polyfill-manager.js

SUP-39283: remove dependancy of Babel/Polifill

---

package.json
src/common/polyfills/polyfill-manager.js

Reverts kaltura/kaltura-player-js#652

Revert "SUP-39283: remove dependancy of Babel/Polifill"

---

.github/workflows/run_canary.yaml

fix(FEC-13390): add canary workflow that uses script from common

---

.github/workflows/run_canary.yaml

This reverts commit 0547a5b7eb73ec9fea5431517c3a47b726ebe336.

Revert "fix builds (#656)"

---

ts-typed/player-config.d.ts
types.d.ts

update `types.d.ts` and `player-config.d.ts` files

feat: update d.ts files

---

package.json
yarn.lock

resolves: https://kaltura.atlassian.net/browse/FEC-13464

fix(FEC-13464): Upgrade shaka latest

---

flow-typed/types/playlist.js
src/common/playlist/playlist-manager.js

solves: https://kaltura.atlassian.net/browse/FEC-13450

feat(FEC-13450): resume playlist from last entry

---

flow-typed/types/playlist.js
src/common/playlist/playlist-manager.js

Since KMS might have old entries played in V2, it may break when playing in v7

feat(FEC-13450): revert changes for playlist

---

types.d.ts

resolves: https://kaltura.atlassian.net/browse/FEC-13509

fix(FEC-13509): upd TS types

---

.github/workflows/update_dependencies.yaml

solves: https://kaltura.atlassian.net/browse/FEC-13477

fix(FEC-13477): update dependencies script

---

.gitignore
demo/index.html
package.json
src/kaltura-player.ts
src/types/ui-config.ts
yarn.lock

Related PRs:
https://github.com/kaltura/playkit-js/pull/745
https://github.com/kaltura/playkit-js-providers/pull/232
https://github.com/kaltura/playkit-js-hls/pull/216
https://github.com/kaltura/playkit-js-dash/pull/258

fix(FEC-13611): Revert babel targets

---

package.json
yarn.lock

sup-39894: patch from version 3.14.4

---

.github/workflows/run_canary.yaml

Update run_canary.yaml - remove specific version - restore to canary

Update run_canary.yaml - remove specific version - restore to canary

---

tests/e2e/common/playlist/playlist-manager.spec.ts

Fix endless loop test in playList

---

package.json
yarn.lock

fix(FIX-Canary): fetch the fixed ui version

---

package.json
yarn.lock

fix(FEC-13669): Aligning all repos with the latest kaltura-browserslist-config to eliminate different browser target among repos

---

src/common/playlist/playlist-manager.ts

fix(FEC-13676): Set document entry duration to 10s

---

.eslintrc
demo/player-ott.html
demo/player-ovp.html
package.json
src/common/cast/player-snapshot.ts
src/common/cast/remote-player.ts
src/common/playlist/playlist-manager.ts
src/common/playlist/playlist.ts
src/common/thumbnail-manager.ts
src/common/utils/setup-helpers.ts
src/kaltura-player.ts
src/ott/poster.ts
src/ovp/poster.ts
src/types/kaltura-player-options.ts
src/types/media-config.ts
src/types/playlist-object.ts
src/types/playlist/KPPlaylistObject.ts
src/types/sources-config.ts
yarn.lock

Aligen kaltua-player-js with the new changes provide
Related PR:
https://github.com/kaltura/playkit-js-providers/pull/236
https://github.com/kaltura/playkit-js-ui/pull/855

fix(FEC-13671): Aligen kaltua-player-js with the new changes provider

---

src/common/cast/remote-control.ts

issue:
chromecast not working
fix:
change ui to fix ui changes
change mediaInfo to get url as chromecast api required to fix session_error
fix issues with reconnect (refresh and disconnect-connect)

fix(SUP-39804): Chromecast Not Working

---

src/common/plugins/plugin-manager.ts
src/kaltura-player.ts
src/types/events/event-types.ts

fix(FEC-13690): Report plugin loads to Kava

---

package.json
yarn.lock

upgrade hlsjs version to v1.5.8

fix(FEC-13879): upgrade hlsjs to v1.5.8

---

package.json
yarn.lock

fix(SUP-42596):Upgrade Shaka version

---

package.json
yarn.lock

fix/FEC-13956: add window before window.MediaSource

---

src/common/utils/kaltura-params.ts

feat(FEC-13839): Take referrer from BE in iframe embed

---

src/common/utils/kaltura-params.ts

fix/FEC-14016: ignore backend referrer since its cached

---

src/common/cuepoint/cuepoint-manager.ts

New logic of cues removing
**Issue:**
**Fix:**
Resolves https://kaltura.atlassian.net/browse/SUP-42321

fix(SUP-42321): fix loop issue on removing cue

---

src/common/utils/kaltura-params.ts

Reverts kaltura/kaltura-player-js#797

Revert "fix/FEC-14016: ignore backend referrer since its cached"

---

demo/player-ovp.html
src/common/utils/kaltura-params.ts
src/kaltura-player.ts

feat(FEC-14049): add referrer to getPlaybackContext

---

src/common/playlist/playlist-manager.ts

Verify that dash sources are set and that the entry is not live before passing it to setCachedUrls
Resolves FEC-14051

fix(FEC-14051): Player v7 | Playlist dash | Errors in consol when playing playlist with dash player on chrome, edge and safari.

---

src/kaltura-player.ts
src/types/playback-config.ts

Add a flag to toggle setCachedUrls API

fix: add enableCachedUrls configuration

---

src/common/utils/error-helper.ts

add specific error message to IP restriction block.
part of - https://github.com/kaltura/playkit-js/pull/791, https://github.com/kaltura/playkit-js-ui/pull/936
[SUP-43014]: https://kaltura.atlassian.net/browse/SUP-43014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-43014): [elearning] specified error message for v7 for IP restriction

---

docs/events.md

Fix broken link to playkit-js events list

chore: update events.md

---

package.json
yarn.lock

Reverts kaltura/kaltura-player-js#893

Revert "chore: trigger custom canary build" (#893)

---

src/common/utils/kaltura-params.ts

fix(CR-259): clipFrom and seekTo must be int

---

package.json
yarn.lock

Reverts kaltura/kaltura-player-js#928

Revert "chore: upgrade kaltura-player dependencies"

---

package.json
yarn.lock

Reverts kaltura/kaltura-player-js#929

chore: upgrade kaltura-player dependencies

---

package.json

add kaltura dep to package.json

---

src/common/utils/setup-helpers.ts

Restore the usage of log handler to its state before this commit 
https://github.com/kaltura/kaltura-player-js/commit/349a917df334e6c466a116c1b030c203dea62295#diff-512652c4c402aacf383ebc385a9f5685566ac2941bb611ae9761edc51c342e62L294
This means that we ALWAYS log to console, unless log.handler configuration is explicitly set
Resolves FEC-14479

fix(FEC-14479): Revert debugInfo log handler

---

src/common/utils/setup-helpers.ts

- Set useDebugInfo to be true by default
- Add logs to debugInfo object
Resolves FEC-14487

fix(FEC-14487): Set debug info to be active by default + restore logs into debug info

---

src/common/storage/local-storage-manager.ts

Reverts kaltura/kaltura-player-js#993

Revert "fix(FEC-14477): When turning on captions using CC button, after refresh captions are off again"

---

src/common/utils/error-helper.ts

Reverts kaltura/kaltura-player-js#1026

Revert "fix(SUP-48817): Entries Under Moderation Are Still Playing"

---

package.json
yarn.lock

upgrade hls version
[SUP-49180]: https://kaltura.atlassian.net/browse/SUP-49180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-49180): [Vanguard] VOD entries distorted
