kaltura/kaltura-player-js

- src/common/utils/external-stream-redirect-helper.js
Change logic to redirect only when configured.
> fix(FEC-8026): external OTT VOD/Live media doesn't works on IE 11

- src/common/utils/external-stream-redirect-helper.js
The default redirect handler should always be setup, as it is a fallback for manifest load error.
If `forceRedirectExternalStreams` it means application wants it to be utilized in advanced, even before an error occurred.
> fix: always set default external stream handler

- src/common/utils/setup-helpers.js
- src/common/utils/ui-actions.js
- src/kaltura-player.js
Before calling the provider to get the media config, update the loading spinner state of the ui manager using the setConfig API.
Also, moved all UI logic to ui-actions file.
> feat(FEC-8084): add loading spinner while preforming change media

- src/common/utils/setup-helpers.js
Configures the delayInitUntilSourceSelected property for the ads plugin based on the runtime platform and the playsinline config value.
> fix(FEC-8131): skippable ads fail on iOS

- package.json
Move `babel-plugin-transform-object-rest-spread` to devDependencies
> chore: move babel-spread package to dev dependencies

- src/common/plugins/plugins-config.js
- src/common/plugins/plugins-config.json
- src/common/utils/kaltura-params.js
* acquire the `referrer` from the `document.URL` unless is an iframe then acquire it from `document.referrer`
* limit the referrer to 1K length 
* pass the referrer to kanalytics plugin via config see https://github.com/kaltura/playkit-js-kanalytics/pull/31
> fix(FEC-8228): calculate correct referrer param for inline and iframe embeds

- src/common/plugins/plugins-config.js
- src/common/plugins/plugins-config.json
pass the `serviceUrl` to ottAnalytics config
> fix(FEC-8235): remove default service url from OTT provider and analytics

- src/common/utils/external-stream-redirect-helper.js
Add support for the jsonP redirect API for OTT Phoenix API.
This API matches the abilities OVP platform has(introduced in #85), but differ in the response body format.
> feat(FEC-8281): support jsonP redirect for OTT

- src/common/ui-wrapper.js
- src/kaltura-player.js
reset the error state when loading a new media
depends on https://github.com/kaltura/playkit-js-ui/pull/249
> fix(FEC-7971): change media doesn't work after a critical error

- src/common/ui-wrapper.js
- src/kaltura-player.js
- test/src/common/utils/ui-wrapper.spec.js
take the ui config from the player config instead of from the ui config which could be irrelevant
> fix(FEC-8355): on change media the config hold the old seekbar configuration

- src/common/ui-wrapper.js
check vr plugin exists and not disable before handling it
> fix(FEC-8382): stereo icon displayed on iPhone, even if VR plugin disabled

- package.json
- yarn.lock
> fix(FEC-7887, FEC-7953, SUP-14111): upgrade hlsjs to 0.10.1

- samples/ovp/cast.html
- src/common/playlist/playlist-manager.js
- src/kaltura-player.js
do not call to `addBindings` if playlist isn't configured
> fix(FEC-8698): when ui is disabled, playNext() called even when playlist isn't configured

- src/common/utils/setup-helpers.js
- src/setup.js
We moved the creation of the video element next to to the autoplay check, which resolved this issue change media issue. so this click handler isn't needed anymore.
> fix(FEC-8714): 'onclick' handler for iOS is not needed

- src/common/storage/storage-manager.js
- test/src/common/storage/storage-manager.spec.js
Manipulate the muted value saved in the local storage in case user changed volume.
> fix(FEC-8773): local storage mute state is not updated when user drag volume bar

- src/common/cast/remote-control.js
flip if-else and check for ```playerConfig.cast.advertising```
>  fix: undefined error incase advertising vast wasn't configured

- src/common/cast/remote-control.js
remove skipping ads on cast disconnect, as is already handled in https://github.com/kaltura/playkit-js-ima/pull/87 according the `startTime` configuration.
> feat(FEC-8751): add support for ima playAdsAfterTime setting

- samples/style.css
Currently we set `text-align: center;` for the `body`, this style is *application* style and hides some bugs from our eyes (e.g. https://github.com/kaltura/playkit-js-ui/pull/327, https://github.com/kaltura/playkit-js-ui/pull/331).
> fix: remove applicative style

- src/common/playlist/playlist-manager.js
pass the current session object to `setMedia` api
> playlist - the thumbnail slices request is missing ks when the item is already played

- src/kaltura-player.js
- test/src/setup.spec.js
postpone the `sources` config after the ui initialization
> fix(FEC-8298): SOURCE_SELECTED event triggered before the UI ready when the source provided manually

- src/kaltura-player.js
Pass plugins with empty config to evaluation as we do for single media (in `setMedia`)
> fix(FEC-8981): playlist doesn't send ott analytics

- src/kaltura-player.js
The entryId is not being evaluated as the dictionary sent to the evaluation was changed and it didn't include the new entry ID.
All analytics plugins are validating that they have a valid entry ID and because they don't then no event is fired.
> fix(FEC-9002): analytics aren't being sent

- src/common/utils/setup-helpers.js
set default value in ima plugin (https://github.com/kaltura/playkit-js-ima/pull/103) instead in kaltura player.
delayInitUntilSourceSelected will be set to true always by default.
> fix(FEC-9013): [iOS] - Player doesnt play ads native

- src/kaltura-player.js
Fullscreen will apply to kaltura container instead user container.
> fix(FEC-9026): [Player_V3][Flash] - When clicking fullscreen icon in flash, the player area stays in the same size

- src/common/utils/setup-helpers.js
config hls by default `autoStartLoad:false` to enable https://github.com/kaltura/playkit-js-ima-dai/pull/15 to override the [`startPosition`](https://github.com/video-dev/hls.js/blob/master/docs/API.md#startposition) value.
> fix(FEC-9087): IMA DAI - the pre-roll Ad duration also calculated for start position - the playback started from 10th sec instead of 20th

- src/common/utils/setup-helpers.js
UA of webos v.2 is fake to safari, added check for mac os to prevent this fake.
LG check is added to UAParser.
> fix(FEC-9118): External caption doesn't display on smart TV

- src/common/utils/setup-helpers.js
change default configuration for LG TV to play with native video player by default instead hls/shaka. Currently we use this only when playing ads.
> fix(FEC-9114): live doesn't work properly with hls.js on WebOS

- src/common/utils/setup-helpers.js
set `playback.inBrowserFullscreen` instead of `ui.components.fullscreen.inBrowserFullscreenForIOS`
> fix: inBrowserFullscreen path

- src/common/utils/setup-helpers.js
LG SDK 4 break their support on base64 source which included in our check for autoplay
> fix(FEC-9260): Autoplay is not working on LG TV

- src/common/utils/setup-helpers.js
config `disableMediaPreload:true` for ios + playsinline is false
> fix(FEC-9273): playing preroll on AV player (ios+playsinline=false) gets the player stuck

- src/common/utils/setup-helpers.js
force smart TV to play widevine for now, after updating shaka player it'll be resolved.
> fix(FEC-9137): Samsung smart tv doesn't success playing playready 

- src/common/utils/setup-helpers.js
IPAD OS as in IOS capability check failed cause there was user interaction on the player video but there wasn't on the capability check video tag. 
Solved - After clicking on the player video tag set autoplay capability check to true to skip this issue.
> fix(FEC-9389): media playing unmuted after unmute fallback

- src/common/utils/setup-helpers.js
Chromium Edge is supported `Widevine` as well so added default config for Edge to prefer playing `Playready`(Hardware DRM)
> fix(FEC-9379): Edge chromium should use Playready when exist

- src/common/utils/setup-helpers.js
check for existence string instead boolean
> fix: config incorrect check for keySystem, isn't a boolean

- src/common/utils/thumbs.js
- src/ovp/poster.js
- test/src/ovp/poster.spec.js
Do not add height and width to non kaltura poster url
> fix(FEC-9366): setMedia doesn't get custom poster as string

- src/common/utils/setup-helpers.js
Solution: play playready drm for edge only on windows
Solves FEC-9632
> fix(FEC-9632): edge play playready on mac os when it's not supported

- src/common/utils/setup-helpers.js
Hisense TV can't use our capability check because it couldn't contain base64 as source.
> fix(FEC-9577): Hisense TV playback doesn't work

- .babelrc
- package.json
- yarn.lock
Change the transpile to transpile the es6 get set methods correctly on IE11.
Solve FEC-9489.
> fix(FEC-9489): IE11 proxy issue in get set methods

- src/common/utils/setup-helpers.js
Set the autoplay capability to `false` for native Ios player.
Thanks https://github.com/kaltura/playkit-js/pull/438 the `runCapability` won't run 
Solves FEC-9629
> fix(FEC-9629): Player is not inline when rendered after the DOM loads

- docs/embed-types.md
encoding the config params in the query string handles special characters and is decoded back when set in the player config. No code change is require. Only better documentation
> docs(FEC-9253): add escaping documentation for player config in embedPlaykit service

- .travis.yml
- package.json
TRAVIS_TAG represents with 'v' and we're looking for npm version without 'v' for Jenkins.
build is missing on release, commit dist was missing after post bump was deleted for canary release.
> build: add DIST that was missing after release and send npm tag

- package.json
set the pre-commit step output into variable to keep the default message
> build: avoid output from pre commit step

- src/common/cast/remote-control.js
Update the local player on cast disconnection with the captions from the cast snapshot 
Solves FEC-9631
Related to https://github.com/kaltura/playkit-js-cast-sender/pull/32
> feat(FEC-9631): add support for out of band text tracks on cast sdk

- docs/guides.md
We now have a Kaltura Player ui.md which describes the ui configuration options. Inside there is a link to the previous css customisation md in the ui repo.
> docs: changing reference of ui customisation to local guide

- .babelrc
issue: proxy applied when ui is disable
solution: add loose mode for the class to enable get in the proxy.
> fix: old browser(IE11) get method in proxy doesn't work

- src/kaltura-player.js
Issue: player.destroy() sending invalid 'stop' bookmark with position val 0
Solution: reorder the components destroy/reset since some of them depend on playkit.
Solve: FEC-10455.
> fix(FEC-10455): incorrect order in reset and destroy process

- package.json
- yarn.lock
Issue: encrypted liner channel sometimes constantly changes from buffering to playing
Solution: upgrade shaka - fixes for live and smartTV optimizations - change the default bufferingGoal to 60s as we have for HLS.
Solve: FEC-10435.
> feat(FEC-10435): upgrade Shaka for fixing live issue and optimizations for smartTV

- package.json
- src/kaltura-player.js
- test/src/kaltura-player.spec.js
- yarn.lock
Move `PLAYBACK_START` back to playkit for autoplay flow
(The only reason we moved it to kaltura player is to be aligned with PLAYBACK_ENDED)
Revert part of commit 6217699
Solves FEC-10468
> fix(FEC-10468): PLAYBACK_START not fired on autoplay

- .travis.yml
Issue: provider doesn't update on the canary version.
Solution: point the version against the master will fetch the updated code.
> build: upgrade provider version to master on canary version

- src/common/polyfills/performance-now.js
- src/common/polyfills/polyfill-manager.js
- src/common/polyfills/prepend.js
- src/common/storage/storage-manager.js
Issue: getLogger comes from playkit which loads all the imported files in playkit.js, in that moment polyfill doesn't exist yet which causes crash on IE11.
Solution: remove logger from polyfill.
refactor which relocates logger to Kaltura player will return those logs back.
> fix: incorrect order in import dependencies break IE11

- test/src/setup.spec.js
> test: textStyle from kaltura player has get method which doesn't exist on compared object

- package.json
- yarn.lock
issue: doesn't play DRM on edge chromium.
Solution: upgrade shaka fix the issue on edge chromium, incorrectly detection of edge browser.
> fix: DRM doesn't play on edge chromium

- src/common/controllers/ads-controller.js
Issue: No pre-roll Ad displays for second media.
Solution: Player should notify ad controller that media is ended as we do for ads with post-rolls, used promise implementation on playback ended.
> fix(FEC-10469): pre-roll Ad for playlist displays for each second media instead of for each one

- src/kaltura-player.js
- test/src/kaltura-player.spec.js
Issue: #370 [moved](https://github.com/kaltura/kaltura-player-js/pull/370/files#diff-b20fda8cac0288af75e0f3c4304df5420584de585d923934f9606e3634d2dbf5L302) the redirect default settings from `setup` to `loadMedia`
so `sources` could be `undefined` in kaltura-player constructor  
Solution: pass empty object to `sources` to the local player if it's `undefined`
Solves FEC-10749
> fix(FEC-10749): playlist by sources stuck

- src/common/controllers/ads-controller.js
- test/src/common/ads/ads-controller.spec.js
`sources.startTime` isn't always exists before sources received in the player and also can change from source to source.
Handle the configured ad breaks on `SOURCE_SELECTED` instead on `PLAYER_RESET`.
related to FEC-10686.
> fix(ads-controller): sources.startTime isn't always exists and can change from source to source

- src/common/utils/external-stream-redirect-helper.js
- src/ott/player-defaults.js
- src/ovp/player-defaults.js
- test/src/ott/player-defaults.spec.js
getting the default `sources.options.redirectExternalStreamsHandler` from common (as before https://github.com/kaltura/kaltura-player-js/pull/370)
Solves FEC-10968
> fix(FEC-10968): OTT doesn't have default external-stream-redirect-helper

- src/common/thumbnail-manager.js
- src/kaltura-player.js
Getting `Cannot create property for a non-extensible object` error.
must initialise a member so it will create the object with property.
fixes FEC-11041
> fix(FEC-11041): player fails in IE11

- src/common/thumbnail-manager.js
- test/src/common/thumbnail-manager.spec.js
remove thumbnail height from thumbnail service call due to BE cache issues.
> fix: remove thumbnail height from thumbnail service call

- src/common/utils/setup-helpers.js
Airplay on iOS devices won't work if we are enabling the capabilities check.
If airplay is configured, set the capabilities automatically as follows:
1. `autoplay: false`
2. `mutedAutoplay:` depends on the `playsinline` property.
> fix(FEC-10405): set capabilities manually on iOS devices when airplay is configured

- flow-typed/interfaces/ads-plugin-controller.js
- src/common/controllers/ads-controller.js
Issue: play ad now to use the active plugin with play ad now API.
Solution: instead of empty implementation on ad plugins, implement it only where it's needed, and check if there's plugin with this API available to play the ad.
> fix(FEC-11062): ad layout doesn't work when IMA DAI configured

- src/kaltura-player.js
Issue: bumper preroll doesn't play after ima preroll with playAdsWithMSE.
Solution: playAdsWithMSE detach/attach also for pre-roll, attach/detach should take control only when the media loaded.
> fix(FEC-11089): bumper preroll doesn't play after ima preroll

- package.json
- src/common/utils/setup-helpers.js
- yarn.lock
Added backward support to in setup-helper
depends on https://github.com/kaltura/playkit-js-dash/pull/139
solves FEC-11126
> fix(FEC-11126): moved useShakaTextTrackDisplay from playback.options.playback.options.html5.dash to text

- src/kaltura-player.js
- test/src/kaltura-player.spec.js
Issue: 
1. sources weren't taken for evaluation - 
`setSources` after configure: evaluator needs the config.source but it didn't update cause `setSources` called after.
`setSources` before `configure`: `sourceSelected` called but `entryId` didn't configure yet.
2. plugin doesn't load correctly from `setMedia` -
plugin config passes throw after sources loaded and then the plugin won't load.
Solution: 
Pass sources config to evaluation so plugin and sources will be loaded correctly.
> fix(FEC-11304): missing entryId on plugins

- src/common/cast/base-remote-player.js
- src/common/cast/remote-player.js
Add missing API in base remote player interface.
> fix(FEC-11374): Live DVR starting to cast from beginning of the DVR instead of Live edge

- .flowconfig
- src/common/thumbnail-manager.js
- src/kaltura-player.js
- test/src/common/thumbnail-manager.spec.js
When casting the player doesn't have the playing video to get the height and width. 
The solution is to keep the video height and width before the cast and use it as fallback.
Also found another bug - same issue with duration - caused the preview image to be stuck on first frame.
Solved same.
Solves FEC-11431
> fix(FEC-11431): no preview thumbnails shown when casting on chromecast - regression

- src/common/thumbnail-manager.js
- src/kaltura-player.js
- test/src/common/thumbnail-manager.spec.js
Following https://github.com/kaltura/kaltura-player-js/pull/466, https://github.com/kaltura/kaltura-player-js/pull/471, https://github.com/kaltura/kaltura-player-js/pull/472 - code was refactored so image thumb height is taken from real image sprite. This overrides all issues regarding height miscalculations and the need for videoHeight (which is missing when casting) 
In addition kaltura player was passed to ThumbsManager instead of core player to fix preview image when casting as the duration when casting needs to come from cast player and not the core one.
Solves FEC-11431
> fix(FEC-11431): refactor preview thumb height from real image sprite height

- karma.conf.js
- src/kaltura-player.js
- test/src/kaltura-player.spec.js
Issue :the reset logic is not called in the first press since the _reset stat flag is true 
fix: rest the _reset state to false every time  error occur by listening to all error events dispatched from the player
Resolve FEC-11513
> fix(FEC-11513): Need to click the Retry button twice after error

- test/src/setup.spec.js
Remove references to fontScale to match changes in playkit-js.
Fixes FEC-11510.
Related PRs:
https://github.com/kaltura/playkit-js/pull/603
https://github.com/kaltura/playkit-js-ui/pull/639
> fix(FEC-11510): No default font size selected in cvaa

- docs/adding-vtt-thumbnails.md
update docs
solves: FEC-11547
related pr: https://github.com/kaltura/playkit-js/pull/607
> docs(FEC-11547): The thumbnalils images should be relative to the VTT file adress by default

- src/common/cuepoint/cuepoint-manager.js
- test/src/common/cuepoints/cuepoint-manager.spec.js
following https://kaltura.atlassian.net/browse/FEV-993
When adding cue points to video element text track, if they are added before video is loaded to video tag then the cues are cleared. Need to wait for player.ready()
Also added new api in cuepoint manager - getActiveCuePoints()
Solves FEC-11554
> feat(FEC-11554): delay addCuePoints after media loaded in video

- src/common/thumbnail-manager.js
- src/kaltura-player.js
- test/src/common/thumbnail-manager.spec.js
build the thumbnail url from provider response before the poster manipulation
Solves FEC-11695, FEC-11698
> fix(FEC-11695,FEC-11698): player thumbnail stripe URL changes according to player size

- src/kaltura-player.js
move `setSources` after `configure`
> fix(FEC-11711): loadMedia is triggered before configuration is set from getMediaConfig

- src/common/cuepoint/cuepoint-manager.js
fix `getCuePointById` to return the found cue point
use `some` instead of `forEackh` to break the loop once a cue point found by id
protect the `removeCuePoint`
Solves FEC-11792
> fix(FEC-11792): slides does not appear in dual video

- package.json
- yarn.lock
related to https://github.com/kaltura/playkit-js-dash/pull/178
Solves FEC-11214
Breaking Change - dash not supported on IE11
> feat(FEC-11214): upgrade shaka to 3.3

- src/common/plugins/plugins-config.js
- test/src/common/plugin/plugins-config.spec.js
If an array in plugin config contains an object item, call removeUnevaluatedExpression on it instead of filtering it out
Resolves FEC-9716
> fix(FEC-9716): An array doesn't merged into plugin config

- src/common/utils/setup-helpers.js
set `lowLatencyMode` to false by default in smart TV's
Solves FEC-12000
> fix(FEC-12000): smart tv - dash video not working

- src/kaltura-player.js
issue: Safari doesn’t expose the videoTrack.height/width/bandwidth so youbora doesn;t send the rendition
fix: Expose the element.videoHeight and element.videoWidth (from the playkit)
solves:  FEC-12059
related pr: https://github.com/kaltura/playkit-js-youbora/pull/90
> fix(FEC-12059): [Youbora] Rendition values have a high number of "Undefined data" records

- src/kaltura-player.js
prevent youtube to use thumbnail manager
FEC-12895
> fix(FEC-12895): fix image player thumbnail logic

- src/common/playlist/playlist-manager.js
solves: https://kaltura.atlassian.net/browse/FEC-13241
UI uses incorrect preset for VOD media created from Live medias. Playlist multirequest contains outdated data about media type (Live instead of VOD), so "type" and "dvr" keys omitted (values uses from baseEntry multirequest)
> fix(FEC-13241): use medias source data instead of playlist

- package.json
- yarn.lock
Upgrade hls.js to 1.4.11
Related PR: https://github.com/kaltura/playkit-js-hls/pull/208
Resolves [FEC-13212](https://kaltura.atlassian.net/browse/FEC-13212)
Resolves [FEC-13322](https://kaltura.atlassian.net/browse/FEC-13322)
[FEC-13212]: https://kaltura.atlassian.net/browse/FEC-13212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FEC-13322]: https://kaltura.atlassian.net/browse/FEC-13322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-13212): upgrade hls.js to 1.4.11

- src/kaltura-player.js
- types.d.ts
Add ExpandableText type to types.d.ts
Related PRs:
https://github.com/kaltura/playkit-js-navigation/pull/334
https://github.com/kaltura/playkit-js-ui/pull/783
Resolves FEC-13209
> fix(FEC-13209): [Audio Player] adjust full size player UI to entries of audio media type

- docs/configuration.md
- docs/user-preferences.md
- src/common/storage/storage-manager.js
solves FEC-13321
**issue:** 'off' option kept at same field as the language (playback.textLanguage) 
**fix:** captions configuration and  state will be split into two, one state holds whether the captions are displayed or not, another state holds the captions language 
Consequently: the user preferences (cached in local storage) should be followed accordingly
that means that each of thotse state will be kept and consistent regardless of the other
configuration structure  change:
a new field is added: captionsDisplay
` {
playback: {
textLanguage: '',
captionsDisplay: false,
}
}`
related pr: https://github.com/kaltura/playkit-js/pull/722
> fix(FEC-13321): Captions default mode "Off" does not behave as expected

- src/common/playlist/playlist-manager.js
**the issue:**
when listening to `PLAYLIST_ITEM_CHANGED` event for live entry (with VOD recording), the payload does not contain the live entry id, but the vod one. it is requested to know the live entry id as well.
**root cause:**
when switching entries in a playlist, in the 1st switching for each entry-
- `loadMedia` is being invoked
- which triggers `getMediaConfig`
- for live entry it returns its linked vod entry with its sources (as expected)
- then the sources of the playlistItem are being updated with what was returned from `getMediaConfig`
Hence, the live entry id is being overridden by the vod one.
**solution:**
when loading the playlist, we get the "original" list of entry ids of the playlist and we keep it in a private data structure called `mediaInfoList`; since we have access …
> fix(FEC-13347): wrong entry id reported by player when switching entries in playlist

- src/common/thumbnail-manager.js
- src/common/utils/kaltura-params.js
- Support new configurations: `seekFrom` and `clipTo`.
- If configured, chain the values to the playManifest request in order to cut the video.
- Also support cutting the thumbSprite accordingly
**related PR-** https://github.com/kaltura/playkit-js/pull/724
Solves FEC-13420
> feat(FEC-13420): support modifying start and end time of video

- src/common/playlist/playlist-manager.js
Image entries in playlist should always be timed images (with the source having duration) so that the ui shows prev and next buttons for them.
In playlist manager we check for the entry type to see if it's an image, and if so, we set the source duration to imageDuration (a field of the playlist).
At the point where we test this condition, playlistItem might have an empty type field, as its value set only after it's is copied from the source after setMedia. This would fail the condition and have duration stay not set.
The fix is to check the type of the source itself instead of checking the type of the playlistItem.
Resolves FEC-13426
> fix(FEC-13426): Player v7| playlist| image entry cover the whole player and the user cannot navigate to another entry

- src/common/storage/storage-manager.js
- save the playbackRate to localStorage
**related PR:** https://github.com/kaltura/playkit-js/pull/732
Solves FEC-13462
> feat(FEC-13462): save playback rate in local storage

- package.json
- webpack.config.js
**Issue:** _'upload to s3_' job is failing on canary since  it is trying to upload **kaltua-tv-player** file which is not exist 
**Fix:** change the output file name on webpack from **kaltua-ott -player** to **kaltua-tv-player**
> fix(FEC-13609): Fix ott output file name of webpack

- src/common/thumbnail-manager.ts
- src/common/utils/kaltura-params.ts
**Issue:**
a regression following migrating the repository to TS; the functionality of clipping video, using query params, was omitted.
**Fix:**
add back the code that is responsible of clipping the video according to [this PR](https://github.com/kaltura/kaltura-player-js/commit/e53698e786a8873cf25626e6960ef83c3ab19829).
> fix(FEC-13615): clip functionality is missing

- docs/api.md
- src/common/playlist/playlist-item.ts
- src/common/playlist/playlist-manager.ts
- src/common/utils/setup-helpers.ts
- src/kaltura-player.ts
- src/types/playlist/playlist-options.ts
Reverts kaltura/kaltura-player-js#711
> Revert "feat(FEC-13507): Doc entry methods"

- docs/playlist.md
- src/common/playlist/playlist-manager.ts
- src/types/playlist/playlist-options.ts
- **enhancement**
Add the ability to pass an entryId, to playlist API, which the playlist will start playing from.
[FEC-13540]: https://kaltura.atlassian.net/browse/FEC-13540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(FEC-13540): allow passing entry id to start playing the playlist from

- src/index.ts
Expose managers and trigger type generation
Required for FEC-13504
> chore: export storage managers from player

- src/common/storage/base-storage-manager.ts
**Issue:**
Captions style is not saved
The bug only affected captions style because other uses of storage manager used StorageWrapper getItem directly
**Fix:**
Add return statement to BaseStorageManager.getItem and do not use StorageWrapper getItem directly outside of BaseStorageManager.getItem
Resolves FEC-13685
> fix(FEC-13685): Captions advanced settings text style is not saved

- docs/errors.md
Adjust the links in the errors.md file by changing the file extensions from .js to .ts.
> fix(docs): fix links in `errors.md` file

- src/common/utils/error-helper.ts
- src/kaltura-player.ts
inside catch block of `loadMedia`, we classify errors that might come from BE (through provider) as Player errors. However, we would like to recognize them and provide the `category` number that suits them.
**changes:**
- inside catch block of `loadMedia`, before firing the error as `Player` category, try to get the category according to the error payload.
- if category is `2`, it means it is `Service` category that came from `provider`
- code `2001` is block action error
- under `error.code = 2001` we need to distinguish between `SESSION_RESTRICTED` and `COUNTRY_RESTRICTED`
- code `2002` is media is not ready error
- fallback to `Player` category as default
> feat(FEC-13652): add meaningful error message

- src/kaltura-player.ts
when playing a media on a mobile device and exiting the browser- the request is for the mobile device to show the entry name of the media that is played and the thumbnail as the background, in the native device player.
- using `MediaMetadata` object to pass to the `navigator.mediaSession`
- configuring the navigator `mediaSession` in `setMedia` to cover playlist and setMedia use-cases
- in case there is not entry name or poster, resetting to empty string so it will not show the previews information
> feat(FEC-13871): set the entry name to navigator media metadata

- demo/player-ovp.html
- src/common/ui-wrapper.ts
- src/types/global/globals.d.ts
**Issue:** the gloabal back-end var window.__kalturaplayerdata is declared after the player and plugins code in bundle file
**Fix:** set a dedicated var for custom preset
https://github.com/kaltura/playkit-js-audio-player/pull/20
> fix(FEC-13931): Audio player| canary audio player version failed to load

- package.json
- webpack.config.js
- yarn.lock
**the issue:**
for source only entries which we don't know where are the keyframes (i.e. zoom integration), the playback get stuck after making seek several times to different positions in the playback.
**solution:**
after investigating the issue, seems to only be an hlsjs issue, where hls is reducing the max buffer length to a value that is lower than the fragment duration.
when setting hls `enableWorker` configuration to `true`, the issue cannot be reproduced anymore.
at some point we disabled the worker since it stopped working and generated an error to the console (see relevant PR [here](https://github.com/kaltura/playkit-js-hls/pull/212/files)); in the current solution we make the worker work again by resolving the original issue of hls worker & webpak.
**related PR:** …
> fix(FEC-13878): copy the hls.worker.js file

- src/common/plugins/plugins-config-store.ts
- src/common/plugins/plugins-config.ts
- src/kaltura-player.ts
- src/types/kaltura-player-options.ts
**enhancement**
take `width` and `height` from `__kalturaplayerdata.uiConfData` and evaluate them on share config.
> feat(FEC-13944): share and embed plugin to take player ratio to embed code

- src/common/cuepoint/cuepoint-manager.ts
issue:
when play live with slides on ios version 17.4.1 and above page got refreshed and collapsed
fix:
when remove cuepoint from track:
* after cuepoint was removed there is no need to continue checking metadataTracks
* check if cuepoint exist for this specific track and only then remove it
solved [SUP-42321](https://kaltura.atlassian.net/browse/SUP-42321)
[SUP-42321]: https://kaltura.atlassian.net/browse/SUP-42321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-42321):V7 Player Not Working With Latest iOS Version

- src/kaltura-player.ts
**Issue:**
Chapter markers doesn't appear on the seekbar on live entry (that currently not broadcasting)
**Root cause:**
The marker displaying depend on duration promise, if duration from engine and player is not the same, the marker won't be displayed. 
souces.duration on the player contains the live duration and not the vod duration so in case the vod duration different from the live duration comparing the engine and source.duartion always returns false.
**Fix:**
If this is live entry but currently not broadcasting and vod is going to play, change the source.duration to the vod duration.
[SUP-43445]: https://kaltura.atlassian.net/browse/SUP-43445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-43445): Chapter markers does not appear in player scrubber

- package.json
- src/common/playlist/playlist-manager.ts
- src/common/utils/kaltura-params.ts
- src/common/utils/session-id-cache.ts
- src/common/utils/session-id-generator.ts
- src/common/utils/setup-helpers.ts
- src/kaltura-player.ts
- tests/e2e/common/utils/kaltura-params.spec.ts
- yarn.lock
- Add setCachedUrls API, which calls playkit (which calls dash adapter)
- Use API to prepare the next / previous playlist entries for a quick switch
- Change the behavior of session id assignment, so that the url we pass the setCachedUrls will be the same url that is later passed to adapter load()
Related PRs:
https://github.com/kaltura/playkit-js/pull/780
https://github.com/kaltura/playkit-js-dash/pull/262
Resolves FEC-13946
> feat(FEC-13946): Player core - Use shaka preload mechanism during playlist playback

- demo/player-ovp.html
- src/common/plugins/base-plugin.ts
Decoupling Plugins from Audio Player
Related pr:
https://github.com/kaltura/playkit-js-downloads/pull/56
https://github.com/kaltura/playkit-js-share/pull/50
https://github.com/kaltura/playkit-js-audio-player/pull/27
https://github.com/kaltura/playkit-js-transcript/pull/205
> fix(FEC-14000): Decoupling Plugins from Audio Player

- src/common/utils/kaltura-params.ts
- src/kaltura-player.ts
In case of iframe embed, the BE adds a parameter to the bundle window.originalRequestReferrer, this value will be added to api calls from the player to the backend for evaluation of access control request.
**Issue:**
The decision when to send it with API calls to the backend needs to be based if it was supplied in origin
**Fix:**
Send the referrer to the provider only if it was supplied by the backend
> fix(FEC-14049): Send referrer only if supplied as iframe

- src/kaltura-player.ts
**bugfix - regression**
**Issue:**
since the latest player changes, while loading rapt media, the player is not being displayed on the page (blank space).
- as part of the latest changes in bottom-bar comp, we register a new service in the constructor, which uses the `serviceProvider` member of kaltura player
- rapt renders the bottom-bar component before kaltura-player finished initializing - `serviceProvider` is `undefined`, which causes a runtime error
**Fix:**
move `serviceProvider` initialization before initializing the ui.
> fix(FEC-14093): rapt is not loading on latest player

- package.json
- src/common/thumbnail-manager.ts
- src/ovp/poster.ts
- tests/e2e/common/thumbnail-manager.spec.ts
- tests/e2e/ovp/poster.spec.js
- yarn.lock
bugfix
**Issue:**
when building `poster` and `sprite` URLs, we are using the `poster` as the base url and then appending params to it (height, width, ks). But, when poster has already been manipulated and we try to build it again, we re-append the params.
**Fix:**
use `rawThumbnailUrl` as the base url to build the urls.
related PR: https://github.com/kaltura/playkit-js-providers/pull/243
> fix(FEC-14071): thumbnail requests append height, width, ks too many times

- src/common/ui-wrapper.ts
- src/kaltura-player.ts
- src/types/global/globals.d.ts
**Issue:**
when there 2 or more different players on one page, video player is not loaded fine
**Fix:**
add the audio preset on new global variable according to the player targetId
pr related - https://github.com/kaltura/playkit-js-audio-player/pull/32/files
[SUP-44085]: https://kaltura.atlassian.net/browse/SUP-44085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-44085): Two different players on the same page

- src/kaltura-player.ts
export changeChildQuality function
part of - https://github.com/kaltura/playkit-js/pull/793/files, https://github.com/kaltura/playkit-js-dual-screen/pull/155
[SUP-38407]: https://kaltura.atlassian.net/browse/SUP-38407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-38407): [GaTech] [Multistream - V7 Player] Child entries not loading high quality flavor assets

- src/common/utils/kaltura-params.ts
- tests/e2e/common/plugin/plugins-config.spec.ts
- tests/e2e/common/utils/kaltura-params.spec.ts
**Issue:**
When open player iframe on new tab, its referrer is kaltura.com, in such case site based access control will reject it.
**Fix:**
If we are in friendly iframe and domain is kaltura.com, we ignore it and return the domain that the backend embed inside the iframe bundle
> feat(FEC-14189): Ingore referrer kaltura.com in friendly iframe 

- src/kaltura-player.ts
If sources.seekFrom or sources.clipTo is set
- Ignore the manifest text tracks, which will cause the playkit player to add external text tracks according to the getPlaybackContext captions metadata
- Pass seekFrom and clipTo to the playkit player so that it will filter and shift the caption cues according to the new time range
Related PR: https://github.com/kaltura/playkit-js/pull/798
> fix(SUP-37490): Align captions with clipTo/SeekFrom Values in PlayManifest

- src/common/utils/error-helper.ts
Adding error messages to site restriction and scheduled restriction
Part of - https://github.com/kaltura/playkit-js-ui/pull/970, https://github.com/kaltura/playkit-js/pull/805, https://github.com/kaltura/playkit-js-providers/pull/245
Resolves [SUP-45003](https://kaltura.atlassian.net/browse/SUP-45003)
[SUP-45003]: https://kaltura.atlassian.net/browse/SUP-45003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-45003): [IKEA Ingka] - past scheduled embedded entries will show a wrong error message for V7 player

- src/kaltura-player.ts
- tests/e2e/kaltura-player.spec.ts
- tests/e2e/mock-data/media.js
shouldAddKs to be based on if the session contains ks instead of session.isAnonymous === false
Related PR: https://github.com/kaltura/playkit-js-providers/pull/259
[FEC-14248](https://kaltura.atlassian.net/browse/FEC-14248)
[FEC-14248]: https://kaltura.atlassian.net/browse/FEC-14248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-14248): shouldAddKs to be based on if the session contains ks

- package.json
- yarn.lock
> update ui version

- demo/player-ovp.html
- src/common/utils/setup-helpers.ts
- src/setup.ts
**Issue:**
https://kaltura.atlassian.net/browse/FEC-14415
Players calls are being blocked by proxy, since first call is a complex POST call,
To overcome it, we need the first call to be an HTTP GET call.
**Fix:**
User can add config - 
provider: {
env: {
initCallToServer:    "/service/system/action/getversion"
}
}
Once this is added, the first api call to the server will be to <serverURL>**/service/system/action/getversion/f**ormat/1
> feat(FEC-14415): Add option for initial HTTP GET api call to server

- package.json
- src/common/thumbnail-manager.ts
- yarn.lock
**Issue:**
`seekFrom` and `clipTo` are not always configured on player level, they might be configured on media level using `loadMedia` api. see following example:
```
player.loadMedia({entryId: '1_xxx'}, {seekFrom: 10, clipTo: 72});
```
currently, in case it comes from the `mediaConfig`, the values do not exist on player level so the thumbnail sprite is wrong and does not include the clipping points.
**Fix:**
save `clipData` from `mediaConfig` or player configuration as fallback.
[CR-200]: https://kaltura.atlassian.net/browse/CR-200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(CR-200): fix clipped thumbnail sprite

- src/common/utils/setup-helpers.ts
- src/setup.ts
- Added the option to get the parameter for `endTime`.
Related PRs: https://github.com/kaltura/playkit-js/pull/814
[FEC-14432](https://kaltura.atlassian.net/browse/FEC-14432)
[FEC-14432]: https://kaltura.atlassian.net/browse/FEC-14432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(FEC-14432): Player end time feature

- src/common/utils/error-helper.ts
Issue:
Blocked Access Control error is not supported.
Fix:
Add support to new Error type
solved [SUP-48028](https://kaltura.atlassian.net/browse/SUP-48028)
related PRS:
https://github.com/kaltura/playkit-js/pull/816
https://github.com/kaltura/playkit-js-ui/pull/1014
[SUP-48028]: https://kaltura.atlassian.net/browse/SUP-48028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: (SUP-48028): Player V7 does not display access control message

- .gitignore
- demo/player-ovp.html
- src/common/utils/setup-helpers.ts
- src/kaltura-player.ts
- src/types/log-level.ts
Add a debugInfo field to the player, containing player information including logs
Note - the log handler does not distinguish between different players on one page, so enabling useDebugInfo in ONE player will cause player.debugInfo to contain logs from ALL players
Related PR: https://github.com/kaltura/playkit-js-ui/pull/1012
Resolves FEC-14445
> feat(FEC-14445): Add Debug Info Option to the Player

- src/common/playlist/playlist-manager.ts
- src/kaltura-player.ts
**Issue:**
When an entry that is part of a playlist got an error, it keeps the previous entry instead of the current entry to play.
**Fix:**
Add a case inside playNext, when a playlist that is part of the entry gets error.
solved [SUP-48030](https://kaltura.atlassian.net/browse/SUP-48030)
part of this PR: https://github.com/kaltura/playkit-js-playlist/pull/77
https://github.com/kaltura/playkit-js/pull/817
[SUP-48030]: https://kaltura.atlassian.net/browse/SUP-48030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-48030): player V7 display issue on playlist with blocked and non-blocked content

- src/common/utils/setup-helpers.ts
Since we no longer use the default log handler (because we use a custom handler so we can append to the log buffer), we now have to explicitly call console.log with log messages - even when useDebugInfo is false
Also added use of JSON.stringify in case logger receives an object param
Resolves FEC-14478
> fix(FEC-14478): When log.useDebugInfo is false, the player doesnt print to log 

- src/common/utils/error-helper.ts
Issue: custom error codes returned by the PS backend are not currently matched by any known fronted error handling logic.
Fix: If we got an error from backend which is blocking content but its code does not match to the known codes the player already handles, than we will display a generic error of access control blocked.
solved [SUP-48028](https://kaltura.atlassian.net/browse/SUP-48028)
[SUP-48028]: https://kaltura.atlassian.net/browse/SUP-48028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix (SUP-48028): Player V7 does not display access control message

- src/common/storage/local-storage-manager.ts
When captions are off and the user clicks on the cc button, user caption selection is not saved in localStorage
Before commit https://github.com/kaltura/playkit-js-ui/commit/0aa3d69c287660916a0815b5233730ac1f4757ed#diff-22612db7ea774e3c6e8ffa651e42a8c07285f8e0241a11b93f8d1f50211161ccR116
When captions were turned off and the user would click on the CC button:
1. USER_SHOWED_CAPTIONS event would be fired.
2. The USER_SHOWED_CAPTIONS event handler would add a listener to TEXT_TRACK_CHANGED.
3. showTextTrack would be called and would update the text track selection.
4. TEXT_TRACK_CHANGED would be fired.
5. The TEXT_TRACK_CHANGED event handler would get the new text track selection and save it in localStorage.
However, because we would fire the USER_SHOWED_CAPTIONS event first and then …
> fix(FEC-14477): When turning on captions using CC button, after refresh captions are off again

- src/common/utils/error-helper.ts
Adding error handling to moderation restriction
Part of https://github.com/kaltura/playkit-js/pull/822, https://github.com/kaltura/playkit-js-ui/pull/1053, https://github.com/kaltura/playkit-js-providers/pull/265
[SUP-48817]: https://kaltura.atlassian.net/browse/SUP-48817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-48817): Entries Under Moderation Are Still Playing

- package.json
- yarn.lock
Audio only doesn't play with hls 1.6.0
[SUP-49704]: https://kaltura.atlassian.net/browse/SUP-49704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-49704): [Bloomberg] Latest V7 player does not play audio
